# Comparison of clinical gait speed and free-living step cadence and their ability to predict mortality: A Whitehall II study

The repository includes relevant documentation and code to replicate the analysis conducted in the paper:

**Add paper and doi**

The aim of this paper was to compare the predictive ability and association with all-cause mortality of gait speed measured in clinical setting and step cadence derived from a free-living accelerometer recording. To respond this question, the study uses data from the 2012-2013 wave of the Whitehall II study.

The code is structured as follows:

## Part 0 - Custom functions

-   00a_functions_cleaning.R contains the functions for data cleaning and descriptive statistics report

-   00b_functions_analysis.R contains the functions used in the analysis

## Part 1 - Extract step cadence

-   01_extract_step_cadence.R contains the code to extract step cadence from the output of the OxWearable/Stepcount software (<https://github.com/OxWearables/stepcount>, version 3.13.0).

## Part 2 - Data cleaning

-   02_data_cleaning.R contains the code to prepare the data for analysis and perform various quality checks.

## Part 3 - Descriptive statistics

-   03_descriptive.R contains the code to perform and visualize various descriptive statistics on the study sample.

## Part 4 - Main analysis

-   04a_main_analysis_models.R contains the code to estimate and extract hazard ratio and C-index of the models containing a single gait parameter.

-   04b_delta_c_index_delta_u.R contains the code to assess difference in C-index between models using the delta-U method.

-   04c_delta_c_index_bootstrap.R contains the code to assess difference in C-index between the models using a bootstrap procedure (not reported in the paper).

-   04d_main_analysis_table.R contains the code to produce tables to visualize hazard ratio and C-index.

## Part 5 - Stratified analysis

-   05a_stratified_analysis_models.R contains the code to estimate and extract hazard ratio and C-index in stratified models.

-   05b_stratified_analysis_pvalue.R contains the code to assess difference in C-index between subgroups using the delta-U method.

-   05d_stratified_analysis_plot.R contains the code to produce forest plots to visualize hazard ratio and C-index of subgroups.

## Part 6 - Sensitivity analysis

-   06a_sensitivity_analysis_models.R contains the code to estimate and extract hazard ratio and C-index using additional accelerometer-based step cadence metrics.

-   06d_sensitivity_analysis_plot.R contains the code to produce forest plots to visualize hazard ratio and C-index of additional accelerometer-based step cadence metrics.

## Part 7 - Post-hoc analysis

-   07a_post_hoc_analysis_models.R contains the code to estimate and extract hazard ratio and C-index of the models combing gait parameters.

-   07b_delta_c_index_delta_u.R contains the code to assess difference in C-index between models using the delta-U method.

-   07c_delta_c_index_bootstrap.R contains the code to assess difference in C-index between the models using a bootstrap procedure (not reported in the paper).

-   07d_post_hoc_analysis_table.R contains the code to produce tables to visualize hazard ratio and C-index.
